language: android
jdk: oraclejdk8

notifications:
  email: true

branches:
  only:
    - master

before_install:
  # linux
  - |
    wget -qO- "https://github.com/crazy-max/travis-wait-enhanced/releases/download/v1.0.0/travis-wait-enhanced_1.0.0_linux_x86_64.tar.gz" | tar -zxvf - travis-wait-enhanced
    mv travis-wait-enhanced /home/travis/bin/
    travis-wait-enhanced --version

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-30.0.2
    - android-30
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
  - mkdir -p "$ANDROID_HOME/licenses"
  - cp ./android-licenses/ "$ANDROID_HOME/licenses/"


licenses:
   - '.+'

script:
  ./gradlew clean build

deploy:
  provider: releases
  file_glob: true
  file: app/build/outputs/apk/*.apk
  skip_cleanup: true

  on:
    repo:  khongswee / poc-printmanager
    jdk: oraclejdk8
  api_key:
    secure: 8563273043aef395a8b461e5522328a86335456e