language: android
jdk: oraclejdk8

notifications:
  email: true

branches:
  only:
    - master

before_install:
  # linux
  - |
    wget -qO- "https://github.com/crazy-max/travis-wait-enhanced/releases/download/v1.0.0/travis-wait-enhanced_1.0.0_linux_x86_64.tar.gz" | tar -zxvf - travis-wait-enhanced
    mv travis-wait-enhanced /home/travis/bin/
    travis-wait-enhanced --version

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-30.0.2
    - android-30
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"


licenses:
   - '.+'

script:
  ./gradlew clean build

deploy:
  provider: releases
  api_key: 58277ca4afcaf191e1068ca5389a34e7b965479b
   file: app/build/outputs/apk/*.apk
  file_glob: true
  skip_cleanup: true

  on:
    repo:  khongswee/poc-printmanager
    jdk: oraclejdk8